import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Providers } from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Voltaris",
  description: "Generated by create next app",
  metadataBase: new URL("https://voltaris.gg"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="cache-version" content="1.0.0" />
      </head>
      <body className={inter.className}>
        <Script
          src="/cache-buster.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/payment-error-handler.js"
          strategy="beforeInteractive"
        />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
